[후이] ch12 함수 (p.154 ~ p.166)
woowacourse-study/2022-book-muscle pull request #18
Opened 2022-03-01 06:09 UTC by kwannee

일단 여기까지만 적고 다음 부분은 최대한 빨리 적어 보도록 하겠습니다~ 함수 챕터 넘 길어요...

2022-03-01 15:18 UTC, wonsss commented
안녕하세요. 후이. 명료하게 잘 정리해주셔서 이해하기 쉬웠어요. 고생하셨네요!

함수 선언문과 함수 표현식은 호이스팅 방법이 달라서, 함수 선언문에 대한 호출은 선언 전에 해도 가능하나, 함수 표현식은 반드시 선언 후에 호출해야 한다는 차이가 있군요. 
 
- 그러면, TypeError가 뜨는 실수를 할 일 없도록, 함수 표현식 말고 함수 선언문만 사용해도 좋은 거 아닌가요?
- 그리고 함수 선언문 대신에 함수 표현식을 사용해야 하는 경우는 언제인지 간단히 설명 부탁드려요.

2022-03-01 15:29 UTC, wonsss requested changes
-  함수 선언문을 변수에 할당할 경우 함수 표현식이 되는 건가요? 
함수 선언문은 변수에 할당할 수 없다고 하셨는데, 함수 선언문을 변수에 할당한 형태가 결국 함수 표현식이 된 것 같아서, 약간 헷갈려요.

- 아래와 같은 함수 표현식(?)의 경우, foo()는 호출되나 bar()는 레퍼런스 에러가 뜨며 호출이 되지 않더라구요.  이런 경우 할당한 변수명 외에 함수 이름으로는 호출할 수 없나요? 그리고 그 이유는 무엇인가요?
```jsx
const foo = function bar() {
	console.log('hui');
}
console.log(foo()); // 'hui'
console.log(bar()); // Uncaught ReferenceError: bar is not defined
```

2022-03-02 03:49 UTC, kwannee commented
> * 그러면, TypeError가 뜨는 실수를 할 일 없도록, 함수 표현식 말고 함수 선언문만 사용해도 좋은 거 아닌가요?
> * 그리고 함수 선언문 대신에 함수 표현식을 사용해야 하는 경우는 언제인지 간단히 설명 부탁드려요.

함수 선언문과 함수 표현식은 형태적으로는 사실 큰 차이가 없어요. 
함수 선언문도 사실은  우리가 사용할 때와 실제 형태가 조금 다릅니다.
우리가 사용할 때는 선언문의 형태로 사용하지만, 런타임 시에는 자바스크립트 엔진이 암묵적으로 함수 표현식 형태로 변환을 합니다. 변수명은 함수 이름으로 하고요. 그렇게 되면 함수 표현식과 형태과 완전히 동일해지죠.
```jsx
 // 우리가 사용하는 함수 선언문
function add(x, y){
  return x + y;
}
// 자바스크립트가 암묵적으로 변환하는 함수 선언문
var add = function (x, y){
  return x + y;
} 
```
함수 선언문과 함수 표현식의 차이점은 전자는 함수 호이스팅이 된다는 겁니다. 그래서 실제 선언 이전에 함수를 참조할 수 있죠.
마르코가 말씀하신 것처럼 TypeError를 피하기 위해 함수 선언문만 사용하면 되는거 아닌가 하고 저도 생각했는데요.
더글라스 크락포드라는 개발자는 함수 선언 이전에 함수를 참조해서 호출하는 방식이 기본적인 규칙을 지키지 않는 것이기 때문에 함수 표현식을 사용할 것을 권장한다고 하더라고요.

결론적으로 말하자면 함수 선언문은 js 개발자의 편의성을 많이 봐준 방식인 것 같아요.
좀 더 엄밀하게 코딩을 하고 싶다면 함수 표현식을 사용하는게 좋고, 그냥 그런거 신경 안쓰고 편하게 쓰고 싶으면 함수 선언문을 쓰면 될 것 같아요.

2022-03-02 05:10 UTC, kwannee commented
> * 함수 선언문을 변수에 할당할 경우 함수 표현식이 되는 건가요?
>   함수 선언문은 변수에 할당할 수 없다고 하셨는데, 함수 선언문을 변수에 할당한 형태가 결국 함수 표현식이 된 것 같아서, 약간 헷갈려요.
맞아요 저도 이게 참 헷갈리더라고요. 말장난 같기도 하고... 위 코멘트에도 남겼듯이 함수 선언문과 함수 표현식은 실제의 형태는 같습니다. 함수 선언문으로 해도 어차피 결국 함수 표현식으로 변환되니까요.
자바스크립트 엔진이 두 코드를 읽을 때, 기명 함수 리터럴이 단독으로 있다면 함수 선언문으로 판단해 호이스팅 하고요, 변수에 담겨져 있다면(함수 표현식이라면) 일단 undefined로 초기화 합니다. 그리고 런타임 시에 할당을 하죠.
```jsx
//(기명) 함수 리터럴이자 함수 선언문
function foo() {
  return 'foo'
}
//함수 리터럴, 함수 이름을 생략할 수 있다.
(function (){
  return 'foo'
})
```
한마디로 말하자면 함수 선언문을 변수에 할당하면 함수 표현식이 되는게 맞습니다. 대신 호이스팅 방식이 달라지겠죠. 그렇게 되면 함수 선언문이 아니게 되는거니까 변수에 담을 수 없다고 하는거 아닐까요? 참 말장난 같네요 ㅋㅋㅋ...

> * 아래와 같은 함수 표현식(?)의 경우, foo()는 호출되나 bar()는 레퍼런스 에러가 뜨며 호출이 되지 않더라구요.  이런 경우 할당한 변수명 외에 함수 이름으로는 호출할 수 없나요? 그리고 그 이유는 무엇인가요?
> 
> ```js
> const foo = function bar() {
> 	console.log('hui');
> }
> console.log(foo()); // 'hui'
> console.log(bar()); // Uncaught ReferenceError: bar is not defined
> ```
함수 표현식에서는 호출하고자 하는 함수 이름을 변수명에 담습니다, 
그리고 원래 함수 이름이 들어갈 자리는 생략하는게 일반적이라고 합니다.
그래도 함수 이름을 명시할 수도 있긴 해요. 근데 그렇게 해도 그 함수 이름으로 함수를 호출할 수 있는 스코프가 제한적입니다
```jsx
//함수 표현식
const foo = function bar() {
	console.log('hui');
}
//함수 몸체
//의사 코드입니다.
bar(){
  console.log('hui')
  bar()
}
``` 
bar라는 함수 이름으로 함수를 호출할 수 있는 스코프는 바로 저 함수 몸체라는 영역 밖에 없습니다. 즉 자기 자신의 함수 내부죠.
그렇게 되면 재귀 함수가 되겠죠? 쓰임새가 많지는 않을 것 같아요.
그래서 일반적으로 함수 이름 자리는 생략한다고 합니다. 쓰임새는 적은데 함수 호출명을 헷갈릴 수 있으니까요.

여기서부터는 제 뇌피셜인데요. 애초에 자바스크립트 함수 이름으로 참조할 수 있는 스코프는 해당 함수 내부인 것 같아요. 함수 선언문도 자바스크립트 엔진이 암묵적으로 함수 이름으로 변수를 선언해 거기에 할당하잖아요? 만약 그런 작업이 없었다면 함수 선언문도 함수 이름으로는 해당 함수 내부에서 밖에 호출하지 못했을 것 같아요

2022-03-02 05:39 UTC, wonsss commented
후이! 아주 잘 이해가 됐어요. 상세한 답변 감사합니다. 
답변을 정리하자면, 다음과 같이 요약되겠네요! 덕분에 많이 배웠습니다. 🙇 

- 함수 선언 이전에 함수를 참조해서 호출하는 방식이 기본적인 규칙을 지키지 않는 것이기 때문에, `함수 표현식`을 사용하는 것이 권장된다. 또한, `함수 표현식`의 이점으로, "변수에 함수를 할당할 수 있으므로, 콜백으로 사용이 가능하다, 클로저로 사용이 가능하다" 등이 있다.
- 함수 선언문을 변수에 할당하면 함수 표현식이 되는게 맞다. 대신 호이스팅 방식이 달라진다.
- 함수 표현식에서는 호출하고자 하는 함수 이름을 변수명에 담는다. 그리고 원래 함수 이름이 들어갈 자리는 생략하는게 일반적이다. 
- 함수 표현식에 있던 원래 함수 이름으로 사용할 수 있는 스코프는 해당 함수 본체 내부로서 제한적이다.

2022-03-02 05:39 UTC, merged