[록바 3.1] 딥다이브 ch10 객체 리터럴 (p.124 ~ p.136)
woowacourse-study/2022-book-muscle pull request #24
Opened 2022-03-02 05:11 UTC by lokba

2022-03-02 11:15 UTC, woose28 requested changes
역시 깔끔하게 정리를 해주셨군요.
이번 문서는 Quiz가 있어서 덕분에 생각을 하면서 문서를 읽게 됐습니다ㅎㅎ
고생하셨어요😊

2022-03-02 11:15 UTC, woose28 commented on modern-javascript-deep-dive/lokba/ch10_object_literal.md
> +```
이런 퀴즈 형식 좋네요👍
덕분에 읽을 때 한 번 더 생각하게 됐어요.

2022-03-02 11:15 UTC, woose28 commented on modern-javascript-deep-dive/lokba/ch10_object_literal.md
> +ES6에서는 프로퍼티 값으로 변수를 사용하는 경우, 변수 이름과 프로퍼티 키가 동일한 이름일 때 프로퍼티 키를 생략할 수 있다. 이것을 `property shorthand`라 한다.
이런 문법을 `property shorthand` 하는 군요! 새로운 용어를 배워가네요ㅎㅎ
좋은 정보 고맙습니다😊

2022-03-02 11:15 UTC, woose28 commented on modern-javascript-deep-dive/lokba/ch10_object_literal.md
> +- 클래스
객체 생성 방법이 아주 종류가 많군요ㅎㅎ
위 방법 중에서 저는 주로 `객체 리터럴`, `생성자 함수`, `클래스` 방법으로 객체를 생성했던 거 같아요.

Q. 대부분의 크루들이 `생성자 함수` 대신에 `클래스` 방법을 사용하는 거 같아요. `생성자 함수` 방법으로 코드를 작성하고 객체를 생성하는 것보다 `클래스` 방법을 사용하는 것에 장점이 있어서 그런 거 같은데, 클래스를 사용하는 것에 어떤 장점이 있을까요? 또는 록바가 주로 사용하는 방법과 그 방법을 택한 이유도 궁금합니다.

2022-03-03 04:28 UTC, lokba commented on modern-javascript-deep-dive/lokba/ch10_object_literal.md
> +- 클래스
좋은 질문 감사합니다.

>록바가 주로 사용하는 방법과 그 방법을 택한 이유도 궁금합니다.

인스턴스를 만들어야 하는 상황에서는, `class`를 주로 많이 사용합니다. 
아래 예시를 한번 보겠습니다.

```javascript
//생성자 함수
function Person(name, age) {
  this.name = name;
  this.age = age;

  this.sayHello = () => {
    return `Hello, ${this.name}`;
  };
}

//class
class Person {
  constructor(name, age) {
    this.name = name;
    this.age = age;
  }

  sayHello() {
    return `Hello, ${this.name}`;
  }
}

```
두 가지 방식 모두 new 연산자를 사용하여 인스턴스를 생성할 수 있습니다. 
저는 class 형식이 `나는 class 키워드를 사용하였고 이것을 기반으로 인스턴스를 생성할 꺼야`라는 의도가 더 분명하다고 생각합니다. 
그래서, class형식을 사용합니다. 

<br>

> 생성자 함수 방법으로 코드를 작성하고 객체를 생성하는 것보다 클래스 방법을 사용하는 것에 장점이 있어서 그런 거 같은데, 클래스를 사용하는 것에 어떤 장점이 있을까요? 

사실 저도 해당 부분을 정확히 인지하지 못한 상태입니다. 그리하여 딥다이브 책을 좀 살펴보았습니다.

해당 내용은 p418에 있습니다.

---

### 생성자 함수와 클래스의 차이

클래스와 생성자 함수는 모두 프로토타입 기반의 인스턴스를 생성하지만 정확히 동일하게 동작하지는 않는다. 
**클래스는 생성자 함수보다 엄격하며 생성자 함수에서는 제공하지 않는 기능도 제공한다.**

클래스는 생성자 함수와 매우 유사하게 동작하지만 다음과 같이 **몇 가지 차이**가 있다.

1. 클래스를 new 연산자 없이 호출하면 에러가 발생한다. 하지만 생성자 함수를 new 연산자 없이 호출하면 일반 함수로서 호출된다.

2. 클래스는 상속을 지원하는 extends와 super 키워드를 제공한다. 하지만 생성자 함수는 extends와 super를 지원하지 않는다.

3. 클래스는 호이스팅이 발생하지 않는 것처럼 동작한다. 하지만 함수 선언문으로 정의된 생성자 함수는 함수 호이스팅이, 함수 표현식으로 정의한 생성자 함수는 변수 호이스팅이 발생한다.

4. 클래스 내의 모든 코드에는 암묵적으로 strict mode가 지정되어 실행되며 strict mode를 해제할 수 없다. 하지만 생성자 함수는 암묵적으로 strict mode가 지정되지 않는다.

5. 클래스의 constructor, 프로토타입 메서드, 정적 메서드는 모두 어트리뷰트 [[Enumerable]]의 값이 false다. 다시 말해 열거되지 않는다.

결론 : 생성자 함수와 클래스는 프로토타입 기반의 객체지향을 구현했다는 점에서 유사하다. 하지만 클래스는 생성자 함수 기반의 객체 생성 방식보다 견고하고 명료하다.

총 5가지의 이유가 나열되어있습니다. 이 중에서 3번을 예시를 들어보겠습니다.

```javascript
console.log(Crew);     // ReferenceError : Cannot access 'Crew' before initialization

class Crew{}
```

해당 코드를 보았을 때, `class는 호이스팅이 일어나지 않구나`라고 생각할 수 있습니다. 
**but, 호이스팅이 일어납니다.** 다만, 호이스팅 방식이 let, const 방식과 유사합니다. 
이와 관련되어서, TDZ라는 용어가 언급되는데 추후 내용이기에 그때가서 다시 언급하겠습니다.


TDZ 관련 [링크](https://noogoonaa.tistory.com/78)

2022-03-03 10:27 UTC, woose28 commented on modern-javascript-deep-dive/lokba/ch10_object_literal.md
> +- 클래스
이번 자동차 미션에서 객체 생성에 대해서 고민한 순간이 있었고
또한 객체 리터럴 방식과 나머지 두 방식(생성자 함수, class 키워드)의 차이점은 알겠는데 생성자 함수와 클래스의 차이는 명확히 몰라서 이런 질문드렸습니다. 록바가 선택한 방식과 이유도 궁금했고요ㅎㅎ

> 저는 class 형식이 나는 class 키워드를 사용하였고 이것을 기반으로 인스턴스를 생성할 꺼야라는 의도가 더 분명하다고 생각합니다.
그래서, class형식을 사용합니다.

이런 이유로 록바는 class를 사용하시는군요!
본인만의 뚜렷한 이유가 있는 게 멋지네요👍

여담으로 저도 생성자 함수보다는 class 키워드를 이용하는 것을 선호합니다.
저는 `1) 많은 크루들이 사용하길래 대세를 따라 사용했다.`와 `2) 클래스 기반의 객체 지향 프로그래밍에 더 익숙하다` 이 두 가지 이유 때문입니다ㅎㅎ

록바 덕분에 class를 사용했을 때의 장점도 배워가네요.
감사합니다 :-)

2022-03-03 10:32 UTC, woose28 commented
고생 많으셨어요.
제가 드린 질문 때문에 딥다이브의 다른 챕터를 미리 공부하게 되셨네요, 바쁜 와중에 시간을 너무 빼앗은 거 같아 미안한 마음이 큽니다😔
그리고 록바 덕분에 오늘도 새로 배워가서 고맙습니다.

이만 이번 pr은 머지하겠습니다. 다음 pr에서 봬요~~

2022-03-03 10:32 UTC, merged