[후이 3.4] 딥다이브 ch 12 함수 (p.177 ~ p.188)
woowacourse-study/2022-book-muscle pull request #34
Opened 2022-03-03 18:28 UTC by kwannee

순수 함수 파트가 재밌네요.
자료 찾아가면서 얘기해보는 것도 좋을 것 같아용

2022-03-05 02:02 UTC, wonsss requested changes
후이! 잘 읽었습니다. 리뷰 및 질문 몇 개 남겼습니다.
이번 주도 고생많으셨어요. 주말에는 푹 쉬어용~ 😄

2022-03-05 02:02 UTC, wonsss commented on modern-javascript-deep-dive/hui/ch12_함수.md
> +자기 자신을 호출 하는 함수를 재귀 함수라고 한다. 재귀 함수에서 자기 자신을 호출할 때 사용하는 식별자는 `함수 이름`이다. 앞서 기명 함수 리터럴에서 살펴 봤듯이 함수 이름의 스코프는 함수 본인의 몸체이다. 물론 함수 이름이 아닌 함수 식별자, 즉 할당된 변수명으로도 호출이 가능하다.
"함수 이름의 스코프는 함수 본인의 몸체이다."

아래 코드에서 `함수 이름`은 b를 가리키는 것이고, `함수 식별자(할당된 변수명)`은 a를 지칭하는 것이죠?
따라서 `함수 이름` b를 사용할 수 있는 스코프는 b 함수 몸체 내부로 한정된다는 의미일까요?
```jsx
const a  = function b () {
...
}
```

2022-03-05 02:02 UTC, wonsss commented on modern-javascript-deep-dive/hui/ch12_함수.md
> +함수의 매개변수를 통해 다른 함수의 내부로 전달되는 함수를 콜백 함수라고 한다. 매개변수를 통해 함수의 외부에서 콜백 함수를 전달받은 함수를 고차 함수라고 한다.
고차함수.. 말은 많이 들었지만, 정확한 정의를 몰랐는데(뛰어난 함수인 줄만 알았던... 😿 ) 덕분에 이해했습니다.

함수를 인자로 전달받거나 결과로 반환하는 함수를 고차함수라고 하는 거군요!

찾아보니까 고차함수의 반대 개념은 일차함수라고 부르네요.
아래 코드에서 addTen 함수가 고차함수인 이유는 "add 함수를 인자로 전달받으며, curry 함수를 결과로 반환"하기 때문이라고 이해하면 될까요?
```jsx
const add = (valueX, valueY) => valueX + valueY;  // 일차함수
const curry = (fx, valueX) => valueY => fx(valueX , valueY); // 일차함수
const addTen = curry(add, 10); // 고차함수

console.log(addTen(5)); // = 15
```

2022-03-05 02:02 UTC, wonsss commented on modern-javascript-deep-dive/hui/ch12_함수.md
> +// filter와 reduce의 예시는 상상해보세요!
상상중.. 🤔 💭

2022-03-05 02:02 UTC, wonsss commented on modern-javascript-deep-dive/hui/ch12_함수.md
> +순수 함수는 인수가 동일하면 언제나 같은 값을 반환한다. **오직 매개변수를 통해 함수 내부로 전달된 인수에게만 의존해 값을 생성해 반환**한다. 외부 상태는 전역 변수, 서버 데이터, 파일, Console, DOM 등이 있다. 만약 매개변수에만 의존한다고 해도 실행될 때 마다 값이 달라진다면(예: 현재 시간) 순수 함수가 아니다.
> 순수함수는 오직 매개변수를 통해 함수 내부로 전달된 인수에게만 의존해 값을 생성해 반환한다

우리가 전에 고민했던 것과 관련이 있군요. 저는 view의 메서드를 순수함수처럼 만들었어요. view는 모델을 모르게 하고 컨트롤러를 통해 전달받은 인수로만 실행되도록이요. 

후이는 이번 미션에서 결국 어떻게 하셨나요?

2022-03-05 02:02 UTC, wonsss commented on modern-javascript-deep-dive/hui/ch12_함수.md
> +함수가 외부 상태를 변경하면 상태 변화를 추적하기 어려워진다. 따라서 함수 외부 상태의 변경을 지양하는 순수 함수를 사용하는 것이 좋다.
비순수함수의 경우, 외부 상태를 변경하면 상태 변화를 추적하기 어려워진다는 단점이 있군요.!

2022-03-05 02:02 UTC, wonsss commented on modern-javascript-deep-dive/hui/ch12_함수.md
> +조건문, 반복문은 가독성을 해치고, 변수의 값은 누군가에 의해 언제든 변경될 수 있어 오류 발생의 원인이 될 수 있다.
함수형 프로그래밍을 통해, "조건문과 반복문을 제거할 수 있다"는 말이 잘 와닿지 않습니다. 
예를 들어서 설명해주실수 있으실까용?

2022-03-06 02:13 UTC, kwannee commented on modern-javascript-deep-dive/hui/ch12_함수.md
> +자기 자신을 호출 하는 함수를 재귀 함수라고 한다. 재귀 함수에서 자기 자신을 호출할 때 사용하는 식별자는 `함수 이름`이다. 앞서 기명 함수 리터럴에서 살펴 봤듯이 함수 이름의 스코프는 함수 본인의 몸체이다. 물론 함수 이름이 아닌 함수 식별자, 즉 할당된 변수명으로도 호출이 가능하다.
네 맞습니다. 물론 함수 식별자로도 함수 내부에서 재귀 함수를 호출할 수 있습니다.

2022-03-06 02:24 UTC, kwannee commented on modern-javascript-deep-dive/hui/ch12_함수.md
> +함수의 매개변수를 통해 다른 함수의 내부로 전달되는 함수를 콜백 함수라고 한다. 매개변수를 통해 함수의 외부에서 콜백 함수를 전달받은 함수를 고차 함수라고 한다.
제가 작성한 요약에서는 고차함수의 정의로 인자로 함수를 전달 받는 함수만을 들었는데요, 찾아보니까 함수를 리턴하는 함수도 고차함수라고 한다네요! 

그런 점에서 보자면 addTen은 값인 5를 받아, 15를 리턴하기 때문에 고차함수라고 보기 어렵지 않을까요? curry는 고차함수가 맞을 것 같습니다.

저도 고차함수에 대한 이해가 부족해서 그렇다 아니다 말씀드리기가 좀 조심스럽네요ㅋㅋ...

[고차함수](https://blog.bitsrc.io/understanding-higher-order-functions-in-javascript-75461803bad)

2022-03-06 02:25 UTC, kwannee commented on modern-javascript-deep-dive/hui/ch12_함수.md
> +// filter와 reduce의 예시는 상상해보세요!
ㅋㅋㅋㅋ 귀찮아서 그런게 절~~대 아닙니다 상상력 자극을 위해서예요 ㅋㅋ

2022-03-06 02:53 UTC, kwannee commented on modern-javascript-deep-dive/hui/ch12_함수.md
> +순수 함수는 인수가 동일하면 언제나 같은 값을 반환한다. **오직 매개변수를 통해 함수 내부로 전달된 인수에게만 의존해 값을 생성해 반환**한다. 외부 상태는 전역 변수, 서버 데이터, 파일, Console, DOM 등이 있다. 만약 매개변수에만 의존한다고 해도 실행될 때 마다 값이 달라진다면(예: 현재 시간) 순수 함수가 아니다.
저도 이걸 보고 나서 view의 메서드들을 순수함수로 만들었습니다~ 근데 모든 함수들을 순수 함수로 만들려니까 좀 힘들었습니다... 처음부터 이 점을 생각하면서 설계를 했어야 되겠더라고요. 그래서 다음 미션부터는 처음부터 함수형 프로그래밍을 염두하며 구현을 해나가보려고요ㅋㅋ

2022-03-06 03:44 UTC, kwannee commented on modern-javascript-deep-dive/hui/ch12_함수.md
> +조건문, 반복문은 가독성을 해치고, 변수의 값은 누군가에 의해 언제든 변경될 수 있어 오류 발생의 원인이 될 수 있다.
답변을 드리기에 앞서 저도 이 부분에 대한 이해가 부족하다는 점을 알려드립니다 ㅋㅋ 그냥 제 생각을 적어볼게요! 참고만 해주세요.

일단 보조함수에 대해서 먼저 설명을 드려야 할 것 같아요. 책에 보조 함수의 정의가 나와 있지 않아서 저도 이 부분이 굉장히 헷갈렸거든요...
```jsx
const complexConditionalStatements = () => {...} // 보조 함수, 굉장히 복잡한 조건문이라고 상상해주세요!

const filter = (value, predicate) => {
  // ... 
  return predicate(value) ? value1 : value2;
};

filter(10,complexConditionalStatements)
```
위의 코드처럼 인자로 넘겨지는 함수를 보조 함수, 영어로는 predicate 라 한다고 합니다.
어 저거 그냥 validator를 따로 만들어두면 되는거 아닌가? 할 수 있는데요. 그렇게 되면 함수의 통제 영역 외부의 무언가로 함수의 리턴 값이 달라지기 때문에 순수 함수라고 하기 힘들 것 같습니다. 순수 함수는 입력 값이 같을 때 늘 출력 값이 같아야 하니까요.

조건문과 반복문을 제거해야 하는 이유가 가독성을 해치기 때문이잖아요? 만약 위의 보조 함수인 조건문 내부가 굉장히 복잡한데, 함수 내부에서 저걸 구현해야 했다면 가독성을 크게 해쳤을 것 같습니다. 물론 위 예에서도 조건문을 완전히 제거하지는 못했어요. 아직 적절한 예시를 생각 못한 걸 수도 있고요... 그래도 가독성은 크게 나아졌다고 생각합니다!

어쨌든 이런 사용이라고 생각합니다. 
함수형 프로그래밍을 사용하면 상태 변경을 추적할 수 있고, 부수 효과를 최소화 할 수 있는 장점이 있지만, 내부 구현이 복잡해 질 수 있다. 이러한 점은 보조 함수를 통해 최대한 해결하도록 한다.

2022-03-06 12:17 UTC, wonsss commented on modern-javascript-deep-dive/hui/ch12_함수.md
> +함수의 매개변수를 통해 다른 함수의 내부로 전달되는 함수를 콜백 함수라고 한다. 매개변수를 통해 함수의 외부에서 콜백 함수를 전달받은 함수를 고차 함수라고 한다.
아하 curry 가 고차함수겠네요! 알려주셔서 감사해요

2022-03-06 12:22 UTC, wonsss commented on modern-javascript-deep-dive/hui/ch12_함수.md
> +조건문, 반복문은 가독성을 해치고, 변수의 값은 누군가에 의해 언제든 변경될 수 있어 오류 발생의 원인이 될 수 있다.
오오 보조함수 프레디케트!!! 덕분에 이해했습니다. 리팩토링할 때 적용해볼게요. 제 코드에는 조건문과 반복문이 너무 많아서요ㅜ.ㅠ

2022-03-06 12:22 UTC, merged