[준찌 3.17] 실행컨텍스트
woowacourse-study/2022-book-muscle pull request #59
Opened 2022-03-17 07:17 UTC by juunzzi

366~387입니당!!

2022-03-17 15:57 UTC, woose28 requested changes
실행 컨텍스트 어려운 개념인데 정리를 깔끔하게 해주셨네요👍
준찌 덕분에 다시 복습하게 됐습니다ㅎㅎ

몇 가지 소소하게 코멘트를 남겼어요~
이번 미션이 빡시다 보니, 혹시나 코멘트 남기는 게 부담이 된다면 간단하게 리액션만 남겨주셔도 됩니다ㅎㅎ

오늘도 책 읽느라 고생 많았어요👏👏

2022-03-17 15:57 UTC, woose28 commented on modern-javascript-deep-dive/juunzzi/ch23_실행컨텍스트.md
> +렉시컬 환경은 식별자와 식별자에 바인딩된 값, 상위 스코프에 대한 챀조를 기록하는 자료구조로 `실행 컨텍스트를 구성`하는 컴포넌트다.
오타 발견!

2022-03-17 15:57 UTC, woose28 commented on modern-javascript-deep-dive/juunzzi/ch23_실행컨텍스트.md
> +# 3. 살행 컨텍스트의 생성과 식별자 검색 과정
오오타 발견!

2022-03-17 15:57 UTC, woose28 commented on modern-javascript-deep-dive/juunzzi/ch23_실행컨텍스트.md
> +<img src="./assets/실행컨텍스트.png"/>
사진👍👍

2022-03-17 15:57 UTC, woose28 commented on modern-javascript-deep-dive/juunzzi/ch23_실행컨텍스트.md
> +
이 부분 너무 좋네요!
`자바스크립트는 정적 스코프이다!` 이 말은 처음 접한 거 같아요ㅎㅎ
덕분에 하나 알아갑니다.

클로저가 언급된 김에 클로저 장인 준찌에게 질문드립니다!

Q. 아래 코드에서 increaser 에 할당된 함수 객체의 상위 스코프는 즉시 실행함수 test가 맞을까요ㅎㅎ?(맞다면 코멘트에 당근🥕을 흔들어 주세요~~)

```javascript
const increaser = (function test() {
    let counter = 0;
    
    return function() {
        return ++counter;
    }
}())

console.log(increaser()); // 1
console.log(increaser()); // 2
```

2022-03-17 15:57 UTC, woose28 commented on modern-javascript-deep-dive/juunzzi/ch23_실행컨텍스트.md
> +
> 렉시컬 환경은 실행 컨텍스트에 종속적이지 않다. 그저 참조 될 뿐이다. 그렇기 때문에 누군가에 의해 참조되고 있다면 소멸하지 않는다.

왠지 여기서도 클로저 냄새가... 저한테만 나는걸까요🤔?

```javascript
const increaser = (function test() {
    let counter = 0;
    
    return function() {
        return ++counter;
    }
}())

console.log(increaser()); // 1
console.log(increaser()); // 2
```
위에 있는 코멘트와 똑같은 예제입니다!
여기서 test() 함수는 즉시 실행 함수이므로 실행되고 바로 실행 컨텍스트 스택에서 pop된다.
하지만 increaser에 할당된 함수의 외부 렉시컬 환경 참조 부분에서 test() 함수의 렉시컬 환경을 참조하고 있다.
따라서 test() 함수의 렉시컬 환경은 소멸하지 않는다.

저는 이렇게 클로저랑 연관 지어 생각해봤는데, 준찌 의견도 궁금하네요!

2022-03-17 15:57 UTC, woose28 commented on modern-javascript-deep-dive/juunzzi/ch23_실행컨텍스트.md
> +
> BindingObject의 프로퍼티가 된다. -> 호이스팅에 의해 undefined인 채로 코드 평가 시점에 들어간다.

이 부분 살짝 잘못됐을지도..?

2022-03-17 15:57 UTC, woose28 commented on modern-javascript-deep-dive/juunzzi/ch23_실행컨텍스트.md
> +
정리 깔끔하고 좋네요ㅎㅎ
전역 실행 컨텍스트의 컴포넌트와 함수 실행 컨텍스트의 컴포넌트의 차이가 아래가 맞을까요?

전역 실행 컨텍스트 컴포넌트
- 전역 실행 컨텍스트의 렉시컬 환경은 1) 객체 환경 레코드 2) 선언적 환경 레코드 3) this 바인딩 부분 4) 외부 렉시컬 환경에 대한 참조 부분

함수 실행 컨텍스트 컴포넌트
- 함수 실행 컨텍스트의 렉시컬 환경은 1) 함수 환경 레코드 2) this 바인딩 부분 3) 외부 렉시컬 환경에 대한 참조 부분

적어보니 렉시컬 환경에 대한 차이 같은데... 이걸 컴포넌트의 차이라고 할 수 있나ㅎㅎ?
아니라면 추가적인 공부를 해보고 공유할게요!!

2022-03-17 16:17 UTC, juunzzi commented on modern-javascript-deep-dive/juunzzi/ch23_실행컨텍스트.md
> +렉시컬 환경은 식별자와 식별자에 바인딩된 값, 상위 스코프에 대한 챀조를 기록하는 자료구조로 `실행 컨텍스트를 구성`하는 컴포넌트다.
ㅋㅋㅋㅋ 죄송합니다 리뷰어님..

2022-03-17 16:17 UTC, juunzzi commented on modern-javascript-deep-dive/juunzzi/ch23_실행컨텍스트.md
> +# 3. 살행 컨텍스트의 생성과 식별자 검색 과정
!??!?!?! ㅋㅋㅋㅋ 사실은 오타왕 준찌

2022-03-17 16:19 UTC, juunzzi commented on modern-javascript-deep-dive/juunzzi/ch23_실행컨텍스트.md
> +
🥕🥕🥕🥕🥕🥕🥕🥕🥕🥕🥕🥕🥕🥕 맞는것같습니다!!!!! 그렇기 때문에 중첩함수 말곤 counter 변수에 접근할 수 없게 되는 것 같아요!!

2022-03-17 16:20 UTC, juunzzi commented on modern-javascript-deep-dive/juunzzi/ch23_실행컨텍스트.md
> +
정확히 맞아요... 책 읽어보셨나요? 딱 그렇게 설명되어있어요!!! 부가 설명을 추가하려다가 혼란만 가중시키는 것 같아 안넣었는데 생각해보니 연결지어서 생각을 해봐야겠군요!!!

멋집니다 역시 뷕터1!!

2022-03-17 16:20 UTC, juunzzi commented on modern-javascript-deep-dive/juunzzi/ch23_실행컨텍스트.md
> +
아 맞네요 undefined라고 하면 안되겠군요!!! 실제로 undefined가 아니죠?!

2022-03-17 16:21 UTC, juunzzi commented on modern-javascript-deep-dive/juunzzi/ch23_실행컨텍스트.md
> +
제가 책을 읽고 이해한바와 똑같습니다!!!!! 렉시컬 환경을 구성하는 컴포넌트 (구성요소)가 다르니 그렇게 표현한 것 같아요 !! 헤헤

2022-03-18 05:44 UTC, woose28 commented on modern-javascript-deep-dive/juunzzi/ch23_실행컨텍스트.md
> +
`호이스팅에 의해 undefined인 채로 코드 평가 시점에 들어간다.`
-> 코드 평가 단계에서는 undefined로 안될 거 같아서요!!

2022-03-18 05:46 UTC, woose28 commented
빠르게 코멘트를 달아주셨네요!
고생하셨습니다ㅎㅎ
이만 merge 하도록 할게요~~

2022-03-18 05:46 UTC, merged