[후이 3.17] 딥다이브 ch 22 this (p.342 ~ 358)
woowacourse-study/2022-book-muscle pull request #61
Opened 2022-03-17 16:23 UTC by kwannee

this 완벽 정리

2022-03-17 17:59 UTC, wonsss requested changes
갓 후이의 this 완벽정리!
덕분에 아주 잘 이해됐어요~

2022-03-17 17:59 UTC, wonsss commented on modern-javascript-deep-dive/hui/ch22_this.md
> +    // this는 메서드를 호출한 객체를 가리킨다.
this는 언제나 자신을 호출한 객체(또는 생성할 인스턴스)를 가리키는군요!

2022-03-17 17:59 UTC, wonsss commented on modern-javascript-deep-dive/hui/ch22_this.md
> +strict mode를 적용하면 일반 함수 내부에서는 this에 undefined가 바인딩 된다.
strict mode에서는 this가 undefined로 바인딩되는군요. 그러면 어떻게 객체와 바인딩하나요?

2022-03-17 17:59 UTC, wonsss commented on modern-javascript-deep-dive/hui/ch22_this.md
> +일반 함수에서 this는 전역 객체를 가리킨다. 호출 되는 방식이 함수라면 아묻따 this는 전역이다. 단 strict mode면 this는 undefined이다.
비엄격 모드 하, 함수 내부에 있는 this는 `아묻따` 전역을 가리키나요?

2022-03-17 17:59 UTC, wonsss commented on modern-javascript-deep-dive/hui/ch22_this.md
> +    console.log(this); //{name:'Lee', getName:f}
객체 내부에서 호출한 this는 편안하게 객체를 가리키는군요. good

2022-03-17 17:59 UTC, wonsss commented on modern-javascript-deep-dive/hui/ch22_this.md
> +    }, 100);
또는 화살표 함수를 사용해도 되겠군요.

```js
    setTimeout(() => {
      console.log(this.a); //20
    }, 100);
```

2022-03-17 17:59 UTC, wonsss commented on modern-javascript-deep-dive/hui/ch22_this.md
> +위에서 말했듯이 this에 바인딩 될 객체는 호출 시점에 결정된다. 메서드였다고 하더라도 일반 함수로써 호출됐다면 this는 아묻따 전역 객체를 가리킨다.
- this: "저는 원래 메서드로서 호출됐어여~~ 으아악! 전역 객체 주지 마세요~ 호출한 대상 객체 주시라구여"
- JS: "응~아니야. 너 결국 함수로 호출됐잖아."
- this: "호에엥~ 그걸 어떻게 아셨죠"
- JS: "어디서 속일라 그래~ `후이`님 가라사대! 결국 일반 함수로 호출되는 this는 아묻따 전역 객체를 가리켜야 하는 운명인거야!"
- this는 결국 window가 되었다.

<보이는 라디오 끝>

2022-03-17 17:59 UTC, wonsss commented on modern-javascript-deep-dive/hui/ch22_this.md
> +책에 나와있지는 않지만 이러한 위험이 있어 생성자 함수에서 this를 쓰는 것은 지양해야 할 것 같다. 이 글을 읽고 있는 그대는 어떻게 생각하는가?
new 연산자 없이 호출되어 일반 함수로만 사용되면, this가 그냥 전역 객체를 가리키는 군요. 따라서 내부 프로퍼티와 메서드들도 모두 전역의 것들이 되어버리구요.

생성자 함수에서 this를 잘못 쓰면 아주 무시무시한 위험성이 도사린다는 점, 후이 덕분에 잘 이해했어요.

다만, 이러한 에러를 미리 캐치해주면 사용해도 무방할 것 같아요.
`new.target`이란 속성이 있는데, 이를 활용해보면 어떨까요? 아래 예시 코드처럼요.
[MDN- new.target](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Operators/new.target) 

```js
//생성자 함수
function Circle(radius) {
  // new 연산자 없이 호출되면 아래 조건에서 걸리고 에러 던진다.
  if (!new.target) {
    throw "Circle()은 무조건 new 연산자랑 같이 호출되어야 해!";
  }
  this.radius = radius;
  this.getDiameter = function () {
    return 2 * this.radius;
  };
}

const circle3 = Circle(15);  //에러( Circle()은 무조건 new 연산자랑 같이 호출되어야 해! )
```

2022-03-17 17:59 UTC, wonsss commented on modern-javascript-deep-dive/hui/ch22_this.md
> +apply와 call은 단지 인수를 넘겨주는 방식의 차이 밖에 없다.
apply, call 은 바인딩 및 함수 호출을 다 하고
bind는 함수 호출 없이 바인딩만 하군요.

apply는 인수를 객체, 배열, 유사배열객체로 전달하고
call과 bind는 인수를 콤마(,)로 나열하여 넘겨주는 차이가 있군요.

2022-03-17 17:59 UTC, wonsss commented on modern-javascript-deep-dive/hui/ch22_this.md
> +person의 메서드 foo에서 callback을 실행했으니 this.name이 ‘Lee’로 나오지 않을까? 하하 나오지 않는다. 잘 보면 콜백을 일반함수로 실행했다. 일반 함수로 실행하면 this는 아묻따 뭐???? 🎤🎤🎤 그렇다 전역 객체 (사실 아묻따 아님.. 예외 밑에 나와용). 전역 객체의 name 프로퍼티는 브리우저 창의 이름을 나타내는 빌트인
전역객체~~ 🎤

2022-03-17 17:59 UTC, wonsss commented on modern-javascript-deep-dive/hui/ch22_this.md
> +그 이유는 addEventListener라는 함수가 콜백함수를 처리할 때 this를 타겟 엘리먼트로 바인딩 하도록 정의가 돼 있어서 그렇다.
addEventListener라는 함수가 콜백함수를 처리할 때 this를 `아묻따 전역 객체`가 아닌 `타겟 엘리먼트`로 바인딩 하도록 정의가 되어 있군요!

2022-03-18 05:54 UTC, kwannee commented on modern-javascript-deep-dive/hui/ch22_this.md
> +위에서 말했듯이 this에 바인딩 될 객체는 호출 시점에 결정된다. 메서드였다고 하더라도 일반 함수로써 호출됐다면 this는 아묻따 전역 객체를 가리킨다.
흐뭇~합니다

2022-03-18 05:57 UTC, kwannee commented on modern-javascript-deep-dive/hui/ch22_this.md
> +strict mode를 적용하면 일반 함수 내부에서는 this에 undefined가 바인딩 된다.
일반함수에서는 this를 사용하지 말라는 소리인것 같아요.
```jsx
function foo(){
  'use strict'
  console.log(this)
}
foo() // undefined
new foo() //foo {}
```
생성자 함수에서만 사용하라는 말인듯?!

2022-03-18 05:58 UTC, kwannee commented on modern-javascript-deep-dive/hui/ch22_this.md
> +일반 함수에서 this는 전역 객체를 가리킨다. 호출 되는 방식이 함수라면 아묻따 this는 전역이다. 단 strict mode면 this는 undefined이다.
넹 일반 함수로 호출됐다면 this는 무조건 전역입니다. 다른걸 bind하지 않는 이상...

2022-03-18 05:58 UTC, kwannee commented on modern-javascript-deep-dive/hui/ch22_this.md
> +    }, 100);
바로 반영했습니다~

2022-03-18 05:58 UTC, kwannee commented on modern-javascript-deep-dive/hui/ch22_this.md
> +책에 나와있지는 않지만 이러한 위험이 있어 생성자 함수에서 this를 쓰는 것은 지양해야 할 것 같다. 이 글을 읽고 있는 그대는 어떻게 생각하는가?
이것도 바로 반영했어용~

2022-03-18 06:00 UTC, kwannee commented on modern-javascript-deep-dive/hui/ch22_this.md
> +그 이유는 addEventListener라는 함수가 콜백함수를 처리할 때 this를 타겟 엘리먼트로 바인딩 하도록 정의가 돼 있어서 그렇다.
네 콜백함수는 제어권을 위임하는 거니까 실행하는 주체가 콜백함수를 어떻게 실행할지 결정 하잖아요?
그래서 그 주체가 this를 다른 값으로 바인딩해서 실행하면 this가 전역이 아니게 되는거죠!

2022-03-18 07:38 UTC, wonsss commented
후이~ 완벽한 this였습니다!
앞으로 코멘트 잘 달린 내용을 issues에 문법 키워드 issue를 만들어서 아카키이빙을 해볼까요?

https://github.com/woowacourse-study/2022-book-muscle/issues/63

시험삼아서 만들어봤어요. 앞으로 this 관련해서 새롭게 알게 된 내용은 여기에 코멘트로 계속 덧붙이는거에요!

2022-03-18 07:38 UTC, merged