[준찌 3.18] 딥다이브 ch19(p386 ~ p401)
woowacourse-study/2022-book-muscle pull request #66
Opened 2022-03-19 08:08 UTC by juunzzi

실행 컨텍스트 마무리 + 클로저 스타트 해봤어요 !!! 글이 길수도있으니... 조심조심...

2022-03-20 09:53 UTC, woose28 requested changes
역시 클로저 장인 준찌~~ 
클로저에 대한 명확히 정의해주셔서 좋았습니다!

아 그리고 이번에는 조금 길게 코멘트 남긴 게 있어요ㅎㅎ
하지만, 미션이 우선이니 바쁘시다면 간단히 리액션만 남겨주셔도 됩니다!

주말인데도 책 읽느라 고생 많았어요!!

2022-03-20 09:53 UTC, woose28 commented on modern-javascript-deep-dive/juunzzi/ch24_클로저.md
> +**일반적으로 클로저는 중첩함수가 상위 스코프의 식별자를 참조하고, 외부 함수보다 오래 유지되는 경우로 한정된다**
클로저에 대한 명확한 정의 좋네요!

준찌가 정리해준 내용을 보기 전에 다른 사람이 `2번 같은 상황일 때 이것이 클로저냐?` 질문을 해왔다면, 고민을 했을 거 같아요🤔
하지만 준찌 글 덕분에 명확해졌습니다!

중첩함수이지만, 상위 스코프에 어떤 식별자도 참조하지 않는다면 이는 클로저가 아니다!!

2022-03-20 09:53 UTC, woose28 commented on modern-javascript-deep-dive/juunzzi/ch24_클로저.md
> +
👍👍

2022-03-20 09:53 UTC, woose28 commented on modern-javascript-deep-dive/juunzzi/ch24_클로저.md
> +
Q1에 적혀있는 고민에 대한 해답 Q2가 맞을까요ㅎㅎ?

2022-03-20 09:53 UTC, woose28 commented on modern-javascript-deep-dive/juunzzi/ch24_클로저.md
> +
저는 이거 항상 잊어버리는데, 
그냥 암기하고 있어야겠어요😵‍💫

2022-03-20 09:53 UTC, woose28 commented on modern-javascript-deep-dive/juunzzi/ch23_실행컨텍스트.md
> +
> `선언적 환경 레코드를 갖는 렉시컬 환경`을 새롭게 생성하여 기존의 전역 렉시컬 환경을 교체한다.

위의 말이 항상 맞을까? 항상 기존의 전역 렉시컬 환경을 교체할까? 라는 고민이 생겼습니다!


```javascript
function foo() {
    let x = 10;
    let y = 20;

    if (true) {
        let x = 1;

        console.log(x) // 1
        console.log(y) // 20
    }
}

foo();
```

위 예제 코드에서 if 문의 코드 블록이 실행될 직전에는 실행 컨텍스트 스택과 렉시컬 환경에 대한 참조를 간단히 도식화하면 아래와 같을 거 같아요.

<img width="1000" alt="if 코드블록 실행 전" src="https://user-images.githubusercontent.com/52148907/159156209-468a5cb9-3e3a-414f-9181-4123dc9337fa.png">

이후 if 문의 코드 블록을 실행할 때

> if문의 코드 블록이 실행되면 if 문의 코드 블록을 위한 블록 레벨 스코프를 생성해야합니다. 이를 위해 `선언적 환경 레코드를 갖는 렉시컬 환경`을 새롭게 생성하여 기존의 전역 렉시컬 환경을 교체한다.

이 말이 항상 맞는다면 아래와 같이 도식화를 할 수 있을 거 같습니다.

<img width="1000" alt="가설 1" src="https://user-images.githubusercontent.com/52148907/159156254-f8f73925-69eb-4353-8950-4bf61aec1b52.png">

근데 이런 경우 제 생각에는 코드 블록 내에서 x를 참조하면 10이라는 값이 나올 거 같습니다.

따라서 저는 `if 문의 코드 블록에 의해 생성된 렉시컬환경이 현재 실행 중인 렉시컬 환경을 대체하는 게 아닌가?` 라는 생각이 들었습니다.
이에 대한 도식화 결과는 아래와 같습니다.

<img width="1000" alt="가설 2" src="https://user-images.githubusercontent.com/52148907/159156545-ae0ac5ab-d572-44cc-bbcd-907edb70c985.png">

이런 경우에는 if문 코드 블록 내에서 x를 참조하면 1이라는 결과가 나올 거 같습니다!

### 결론
뇌피셜이지만 생각의 흐름을 나누는 게 또 서로의 성장에도 도움이 되지않을까 해서 적어봐요ㅎㅎ

> if문의 코드 블록이 실행되면 if 문의 코드 블록을 위한 블록 레벨 스코프를 생성해야합니다. 이를 위해 `선언적 환경 레코드를 갖는 렉시컬 환경`을 새롭게 생성하여 기존의 전역 렉시컬 환경을 교체한다.

책에도 위 구문이 적혀있어 확신은 없지만, `위 말이 항상 맞지는 않을 거 같다!` 라는게 제 의견입니다!

정리하자면 제 뇌피셜은 아래와 같습니다.

> if 코드 블록에 의해 생성된 렉시컬 환경은 현재 실행 중인 실행 컨텍스트가 참조하고 있는 렉시컬 환경을 대체한다.

이에 대해서 준찌의 의견이 궁금하네요!!

PS.[여기](https://www.ecma-international.org/publications-and-standards/standards/ecma-262/) 찾아보면 명확히 해답을 알 수 있지 않을까 싶은데...
일단 미션이 우선이니 정답을 찾는 건 패스!!
새로운 내용을 알게 되면 바로 공유하겠습니다ㅎㅎ

2022-03-20 14:56 UTC, juunzzi reviewed
코멘트 달아보았습니다!!

2022-03-20 14:56 UTC, juunzzi commented on modern-javascript-deep-dive/juunzzi/ch23_실행컨텍스트.md
> +
아 헐 ... 그게 맞아요 이거 제가 잘못적었나봐요 ㅠㅠㅠㅠ 동의합니다. 정확히는 현재 실행 중인 실행 컨텍스트가 참조하고 있는 렉시컬 환경을 대체하고 있는 것 같습니다 !!! 

빅터의 말을 보니 너무 정확히 이해됩니다 ... 좋은 빅터만의 자료 감사합니다. 제 정리가 잘 못된 부분이 있어 빅터의 시간을 뺐은게 아닌가 싶네요 ..ㅠㅠㅠ 죄송합니다

2022-03-20 14:56 UTC, juunzzi commented on modern-javascript-deep-dive/juunzzi/ch24_클로저.md
> +
Q1에 대한 해답은 실행 컨텍스트의 `외부 렉시컬 환경에 대한 참조 값을 정할 때` 이 값을 참조하기 위해 라고 정의할 수 있을 것 같습니다.

Q2는 질문이라기 보단 어떤 정리라고 보시면 좋을 것 같네요 

이 또한 혼돈을 주어 죄송합니다 ㅠㅠ

2022-03-20 14:56 UTC, juunzzi commented on modern-javascript-deep-dive/juunzzi/ch24_클로저.md
> +**일반적으로 클로저는 중첩함수가 상위 스코프의 식별자를 참조하고, 외부 함수보다 오래 유지되는 경우로 한정된다**
저도 사실 자바스크립트의 모든 함수(new Function으로 생성되는 함수를 제외하고)는 클로저라는 생각이 있었습니다만, 이 정리를 통해 생각의 전환을 해볼 수 있었던 것 같아요 !! 좋게 봐주셔서 감사합니다 헤헤 비비빅터!

2022-03-21 02:24 UTC, woose28 commented on modern-javascript-deep-dive/juunzzi/ch23_실행컨텍스트.md
> +
시간을 빼앗다니요..!
스스로 생각 정리할 수 있었고, 애초에 준찌 아니였으면 블록 스코프에 대해서 깊게 생각하지 못했을 거예요~~!

> if문의 코드 블록이 실행되면 if 문의 코드 블록을 위한 블록 레벨 스코프를 생성해야합니다. 이를 위해 선언적 환경 레코드를 갖는 렉시컬 환경을 새롭게 생성하여 기존의 전역 렉시컬 환경을 교체한다.

그리고 이 내용이 책에도 명시되어 있는데, 헷갈려서 질문을 드린 겁니다!
준찌가 잘못 적은 게 아니예요ㅎㅎ

아 그리고 혹시나 해서 하는 말인데, 저 이미지는 의견에 대한 설명을 도우려고 제가 만든겁니다ㅋㅋㅋ
그래서 정확하지 않을 수 있어요!

2022-03-21 03:57 UTC, juunzzi commented on modern-javascript-deep-dive/juunzzi/ch23_실행컨텍스트.md
> +
저 코드에대해서만 맞는말인것같아요 ㅋㅋㅋ

2022-03-29 09:42 UTC, woose28 requested changes
으... 제가 리뷰가 너무 늦었네요🙏
에러가 발생하는 예제 코드에 코멘트를 남겼습니다!
확인 부탁드려요ㅎㅎ!

2022-03-29 09:42 UTC, woose28 commented on modern-javascript-deep-dive/juunzzi/ch24_클로저.md
> +
ㅋㅋㅋㅋㅋ우리 잘했다!!
준찌와 클로저를 훈련한 덕분에 이번 자판기 미션에서도 클로저를 활용했습니다ㅎㅎ

2022-03-29 09:42 UTC, woose28 commented on modern-javascript-deep-dive/juunzzi/ch24_클로저.md
> +흠흠.. 메소드와 프로퍼티가 공개적이면, 다른 객체에서도 이를 참조하고 사용할 수 있다는 것이니 상호의존성이 낮음을 보장할 수 없겠군.
깨달음 좋습니다👍

2022-03-29 09:42 UTC, woose28 commented on modern-javascript-deep-dive/juunzzi/ch24_클로저.md
> +```
프로토타입과 같이 활용하는 방법 좋네요!

다만 이 예제 코드에서 `Uncaught TypeError: Counter is not a constructor`가 발생합니다..!

2022-03-30 06:22 UTC, juunzzi commented on modern-javascript-deep-dive/juunzzi/ch24_클로저.md
> +
오 빅터 ㅋㅋㅋ 굳입니다.... 구경하러가겟습니다 ㅋ

2022-03-30 06:26 UTC, juunzzi commented on modern-javascript-deep-dive/juunzzi/ch24_클로저.md
> +```
```jsx
const Counter = (function () {
  //...
  // 수정된 부분
  return Counter;
})();
const counter = new Counter();
console.log(counter.inc()); // 1
console.log(counter.dec()); // 0

```

요렇게 해야 카운터를 제너레이트 하는 함수를 리턴할 수 있겠군요!!! 실수했나봐요 지적감사합니다 비비빅터 !!

2022-03-30 06:30 UTC, merged