[후이 3.21] 딥다이브 ch26 ES6 함수의 추가 기능 (p 469 ~ 491)
woowacourse-study/2022-book-muscle pull request #71
Opened 2022-03-20 19:46 UTC by kwannee

this에서 생긴 의문을 해결했습니다

2022-03-21 08:22 UTC, wonsss requested changes
너무 좋구~

2022-03-21 08:22 UTC, wonsss commented on modern-javascript-deep-dive/hui/ch26_ES6.md
> +따라서 메서드 역시 생성자 함수가 될 수 있었다.
ES6 이전.. 무법천지?

2022-03-21 08:22 UTC, wonsss commented on modern-javascript-deep-dive/hui/ch26_ES6.md
> +일반 함수는 constructor이지만 ES6의 메서드와 화살표 함수는 non-constructor이다. 이에 대해 자세히 알아보자.
일반 함수는 constructor이지만 ES6의 메서드와 화살표 함수는 non-constructor이다! 

아하!

2022-03-21 08:22 UTC, wonsss commented on modern-javascript-deep-dive/hui/ch26_ES6.md
> +};
메서드(ES6에서 축약표현으로 정의됨)와 일반함수는 형식상 이렇게 구분 되고, 생성자 함수가 될 수 있냐 없냐의 차이가 특징적이군요!

2022-03-21 08:22 UTC, wonsss commented on modern-javascript-deep-dive/hui/ch26_ES6.md
> +ES6 메서드는 자신을 바인딩한 객체를 가리키는 내부 슬롯 `[[HomeObject]]`를 갖는다. super 참조는 내부 슬롯`[[HomeObject]]` 를 사용하여 수퍼클래스의 메서드를 참조하므로 내부 슬롯 `[[HomeObject]]` 를 갖는 ES6 메서드는 super 키워드를 사용할 수 있다.
- `[[HomeObject]]` : 자신을 바인딩한 객체를 가리키는 내부 슬롯
	- `super ` 참조 시, 이 `[[HomeOjbect]]`를 사용하여 부모 클래스의 메서드를 참조한다.

띠용~

2022-03-21 08:22 UTC, wonsss commented on modern-javascript-deep-dive/hui/ch26_ES6.md
> +  __proto__: base, // 생성자에 프로토타입을 상속하는 과정
일반 객체에서는 클래스가 갖는 extends 문법이 없으니,
`__proto__` 프로퍼티에 상속받으려는 부모 객체명을 할당함으로써, 생성자에 프로토타입을 상속받는군요?

2022-03-21 08:22 UTC, wonsss commented on modern-javascript-deep-dive/hui/ch26_ES6.md
> +  sayHi() {
sayHi().. 너 신상 `ES6 메서드` 라는 멋진 녀석이었구나..?

그래서 초능력 같은 super()도 쓸 수 있고... 아주 대단해..!

2022-03-21 08:22 UTC, wonsss commented on modern-javascript-deep-dive/hui/ch26_ES6.md
> +이처럼 화살표 함수는 콜백 함수로서 정의할 때 유용하다. 화살표 함수는 표현만 간략한 것이 아니다. 화살표 함수는 일반 함수의 기능을 간략화 했으며, this도 편리하게 설계됐다. 일반 함수와 화살표 함수의 차이에 대해 살펴보자.
화살표 함수 : 콜백함수로 사용하면 좋다. this로 고민할 때 쓰면 더 좋다!

2022-03-21 08:22 UTC, wonsss commented on modern-javascript-deep-dive/hui/ch26_ES6.md
> +   이 부분은 정확하게 이해 되지가 않는다. prototype 프로퍼티와 프로토타입이 뭐가 다른걸까? **proto** 이건가? prototype property vs prototype attribute라는 키워드가 있는 걸 보니 뭔가 다른가 보다. 다음에는 property를 공부해 봐야겠다.
[`__proto__` VS. `prototype`](https://stackoverflow.com/questions/9959727/proto-vs-prototype-in-javascript)
- `__proto__`는 메서드 등을 체인을 타고 찾는데 사용되는 실제 객체이다.
- `prototype`은 `new`로 인스턴스를 만들 때 `__proto__`를 생성하는 데 사용하는 객체다. 
```js
function Foo() {}
console.log(new Foo().__proto__ === Foo.prototype); // true, 인스턴스의 __proto__와 함수의 prototype은 같다
console.log(new Foo().prototype === Foo.prototype); // false, 인스턴스의 prototype과 함수의 prototype은 다르다.
console.log(new Foo().prototype === undefined); // true, 인스턴스의 prototype은 undefined이다(즉, 없다?).
console.log(new Foo() instanceof Foo); // true
console.log(new Foo() instanceof Object); // true
console.log(new Foo().__proto__.__proto__ === Object.prototype); // true
console.log(Foo.__proto__ === Function.prototype); // true

console.log(new Foo().__proto__); //  Foo.prototype과 동일하다
/* {constructor: ƒ}
	constructor: ƒ Foo
	[[Prototype]]: Object */
console.log(Foo.prototype.constructor); // Foo, 함수 정의 반환
console.log(Foo.prototype.__proto__); // {}, 빈 객체 반환,  함수이므로 root level인 Object.prototype을 가리킨다
```

- 함수 정의 코드를 실행하면, 자바스크립트는 해당 함수에 `prototype` 프로퍼티를 추가한다. 해당 `prototype` 프로퍼티는 `constructor`와 `__proto__`라는 두 개의 프로퍼티를 가진 객체다.
	- 브라우저에서 콘솔로 찍으면 `__proto__`는 안 보이고, `[[Prototype]]`만 보여서 이건 또 뭐냐고 물을 수 있다. 사실 둘은 같은 것이다. 정확히 말하면, 	`__proto__`는  `[[Prototype]]`에 대하여 브라우저에서 지원하는 getter이다. `[[Prototype]]`은 private 연결이므로 직접적으로 접근할 수 없다. 
-  `prototype` 프로퍼티는 인스턴스 내에서 사용할 수는 없고, 함수에서만 사용할 수 있다.
- 대신, 인스턴스는 `__proto__`프로퍼티를 통해 함수의 `prototype` 프로퍼티를 참조한다.
- 그리고 함수 `__proto__` 프로퍼티는 더 상위의 Function의 `prototype` 프로퍼티를 참조한다. 따라서 서로 다른 함수의 `__proto__` 프로퍼티들을 비교하면 같음을 확인할 수 있다.
- 즉, `prototype` 프로퍼티는 저장되는 실제 객체인 `__proto__` 프로퍼티를 위한 청사진일뿐이다. 다른 말로 풀자면, `prototype`은 생성자 함수(constructor functions)에서 사용되는 것이며, 이러한 정의를 담는 정확한 용어로 `"prototypeToInstall"`로 했어야 오해가 없었을 것이다.
- 반면, `__proto__`의 정의에 잘 맞는 용어는 `"installedPrototype"`으로 했어야 이해하기 쉬웠을 것이다. 

정리해서, 함수를 `new` 키워드를 사용하여 인스턴스를 만들면 다음과 같은 일이 발생한다.
```js
function SetName(name) {
	this.name = name;
}
const marco = new SetName("Marco");
```
1. 빈 새 객체를 만든다.
2. marco에 `__proto__` 프로퍼티를 만들고, 그  `__proto__` 프로퍼티가 SetName의 `prototype`을 가리키게 한다.
3. 1번에서 만든 새 객체의 context(this)로 `SetName.prototype.constructor` (= SetName 함수정의)가 실행(execute)되며, 이러한 해당 함수정의에 따라 "Marco" 문자열을 전달받은 'name' 프로퍼티가 새 객체에 추가된다. 
4. const `marco`에 해당 새 객체(1번에서 만들어진)가 지정되어 반환된다.. 


- 결론 : 인스턴스는 `__proto__` 프로퍼티만을 제대로 갖고, 클래스와 생성자함수는 추가로 `prototype` 프로퍼티를 갖는다. 인스턴스의 `__proto__` 프로퍼티는 클래스나 생성자함수의 `prototype`을 가리킨다. (사족을 덧붙이자면, 클래스와 생성자함수의 `__proto__` 프로퍼티는 root level의 `Function.prototype` 프로퍼티를 가리킨다.

추가로 Function과 Object의 프로토타입 관계를 `아담과 이브`에 빗대어 살펴보자.
`Object`는 이브이고, `Function`은 아담이다. 아담(`Function`)은 그의 갈비뼈(`Function.prototype`)을 사용하여 이브(`Object`)를 창조하였다. 그러면 아담(`Function`)은 누가 창조했는가? - 자바스크립트 언어를 만든 사람! - 
따라서 아래와 같은 비교 결과가 모두 참이 된다.
```js
console.log(Object.__proto__ === Function.prototype); // true
console.log(Function.prototype === Function.__proto__); // true, 그 위는 없다.
console.log(Object.__proto__ === Foo.__proto__);  // true, 둘 다 Function.prototype을 참조한다.
```

[`__proto__` VS. `constructor.prototype`](https://stackoverflow.com/questions/650764/how-does-proto-differ-from-constructor-prototype)
![image](https://user-images.githubusercontent.com/59413128/159219279-c04a15b5-46f7-4d4f-a393-adb516e5da5e.png)

2022-03-21 08:26 UTC, kwannee commented on modern-javascript-deep-dive/hui/ch26_ES6.md
> +  __proto__: base, // 생성자에 프로토타입을 상속하는 과정
오호 그렇네요? 책에 이 과정에 대한 설명이 없어서 저도 찾아봤었거든요! 이런 이유였네요

2022-03-23 02:09 UTC, kwannee commented on modern-javascript-deep-dive/hui/ch26_ES6.md
> +따라서 메서드 역시 생성자 함수가 될 수 있었다.
약한 자는 살아남을 수 없다. 생성자 함수에 new를 빼먹어? 사형

2022-03-23 02:11 UTC, kwannee commented on modern-javascript-deep-dive/hui/ch26_ES6.md
> +  sayHi() {
sayHi : 훗 super 못 쓰는 일반 함수, 화살표 함수 같은 애송이들이랑은 비교하지 말아줘

2022-03-23 02:12 UTC, kwannee commented on modern-javascript-deep-dive/hui/ch26_ES6.md
> +   이 부분은 정확하게 이해 되지가 않는다. prototype 프로퍼티와 프로토타입이 뭐가 다른걸까? **proto** 이건가? prototype property vs prototype attribute라는 키워드가 있는 걸 보니 뭔가 다른가 보다. 다음에는 property를 공부해 봐야겠다.
집중한 마르코는 2시간 만에 이정도 깨달음이 가능하다...

2022-03-26 06:11 UTC, merged