[준찌 3.30] 프레임워크 없는 프론트엔드 개발 ch1(p21 ~ p41)
woowacourse-study/2022-book-muscle pull request #76
Opened 2022-03-30 08:24 UTC by juunzzi

2022-03-31 15:48 UTC, wonsss reviewed
준찌, 빅터 안녕하세요~ 책이 맛있어서 보여서 읽고 갑니다(총총총)

2022-03-31 15:48 UTC, wonsss commented on frameworkless-frontend/juunzzi/1장_프레임워크에_대한_이야기.md
> +준찌의 사견 : 저도 이 말에 굉장히 공감해요. 뮤지션이 음악을 만들 때, 좋은 음악을 만드는 것에 집중할까요 아님 화성학에 집중할까요? 또 언어를 배울 때 의사소통하는법에 집중해야할까요 아님 문법을 지키는 것에 집중해야할까요. 저도 목적을 잃는게 싫어요. 프레임워크 혹은 디자인패턴 모두 같지 않을까요? 우리의 목표는 사용자에게 좋은 서비스를 제공할 수
준찌 의견 공감합니다!

2022-03-31 15:48 UTC, wonsss commented on frameworkless-frontend/juunzzi/1장_프레임워크에_대한_이야기.md
> +제이쿼리 : 현대 웹 개발의 초석 역할을 수행. 만만히 보고 있지만 역사적으로 꽤나 가치있는 녀석이다. (박지성)
지성팍..? 형이 왜 여기서 나와..? 😮

2022-03-31 15:48 UTC, wonsss commented on frameworkless-frontend/juunzzi/1장_프레임워크에_대한_이야기.md
> +리액트: 가장 인기 있는 프론트엔드 라이브러리 혹은 프레임워크이다. 선언적인 패러다임을 따른다. 돔을 직접 수정하기 보단 상태를 변경하여 리액트가 나머지 작업을 수행할 수 있게한다. 데이터가 모델(상태)->뷰로만 흐르게 된다. 리액트는 프레임워크라기 보단 렌더링 라이브러리이다. (상태만 변경하고 렌더링 함수를 호출하듯 라이브러리 느낌도 있다.)
우와 이런 차이가 있군요(물론 저는 앵귤러, 리액트 다 안 써봄)

앵귤러는 양방향 데이터 바인딩이고, 리액트는 단방향 데이터 바인딩이네요.
따라서, 리액트는 프레임워크보단 라이브러리라고 스스로 지칭하는 거군요?

2022-03-31 15:48 UTC, wonsss commented on frameworkless-frontend/juunzzi/1장_프레임워크에_대한_이야기.md
> +프레임워크를 사용할 때, 지금의 기술투자가 이득을 보이게될지, 프로젝트의 빚이 될지를 적절히 고민해보라는 말 같네요..!
무지성 프레임워크 사용이 아니라,
개발하려는 프로덕트의 여러 특성을 고려하여 적합한 프레임워크를 선택(또는 선택X)하라는 거군요.

 이 책을 통해, 적합한 프레임워크를 선택할 수 있는 지식 및 개발의 본질에 대한 인사이트를 얻을 수 있을 것 같아서 기대되네요.

2022-03-31 16:50 UTC, juunzzi commented on frameworkless-frontend/juunzzi/1장_프레임워크에_대한_이야기.md
> +제이쿼리 : 현대 웹 개발의 초석 역할을 수행. 만만히 보고 있지만 역사적으로 꽤나 가치있는 녀석이다. (박지성)
ㅋㅋㅋㅋ 지성팍이.. 해외축구의 초석을 다졌으니.. 제이쿼리랑 박제이성이랑 비슷해보였어요

2022-03-31 16:57 UTC, juunzzi commented on frameworkless-frontend/juunzzi/1장_프레임워크에_대한_이야기.md
> +리액트: 가장 인기 있는 프론트엔드 라이브러리 혹은 프레임워크이다. 선언적인 패러다임을 따른다. 돔을 직접 수정하기 보단 상태를 변경하여 리액트가 나머지 작업을 수행할 수 있게한다. 데이터가 모델(상태)->뷰로만 흐르게 된다. 리액트는 프레임워크라기 보단 렌더링 라이브러리이다. (상태만 변경하고 렌더링 함수를 호출하듯 라이브러리 느낌도 있다.)
저자가 말하길 리액트에게는 프레임워크 방식, 그러니깐 규칙이 있기 때문에 프레임워크라고 말하고 싶다네요.. 하지만 리액트 팀은 라이브러리라고 하는데 그 이유는 다른 프레임워크에 비해 규칙이나 제약이 떨어져서 그런것 같아요. (이 부분은 사견입니다. 그 팀이 왜 라이브러리라고 하는 지는 명확하지 않아요. 자유도가 높다여서 그런 것 같다는게 제 의견입니다..)

포코가 최근에 말한 Next JS가 대표적인 `프레임워크`인데 제 경험에 빗대어 설명하자면 

명확한 규칙이 있어요. 서버에서 미리 템플릿을 만들어두기 위해 써야하는 메소드 해당 메소드를 쓰면 컴포넌트 단으로 데이터가 어떻게 넘어오는지 등등.. 많은 프레임워크 방식들이 존재하거든요. 요렇게 프레임워크 자체가 정해둔 규칙이 비교적 제약사항처럼 느껴진다면 프레임워크로 부르는게 맞는거 같아요.

(준찌의 사견: 리액트 또한 프레임워크가 맞는 것 같습니다. 그렇다고 해서 라이브러리가 아니라고 할 수 도 없겠네요. 충분한 자유도가 있다고 생각하거든요)

마르코가 또 정의해주셨으면 좋겠네요 ㅋㅋㅋ 리액트가 프레임워크일지 라이브러리일지.. 별로 중요한 사실은 아니겠지만 .. ㅋㅋㅋ

2022-03-31 16:58 UTC, juunzzi commented on frameworkless-frontend/juunzzi/1장_프레임워크에_대한_이야기.md
> +프레임워크를 사용할 때, 지금의 기술투자가 이득을 보이게될지, 프로젝트의 빚이 될지를 적절히 고민해보라는 말 같네요..!
정확히 맞는것같아요 !! 그래서 너무 기대됩니다 ㅋㅋㅋ

2022-03-31 17:02 UTC, wonsss commented on frameworkless-frontend/juunzzi/1장_프레임워크에_대한_이야기.md
> +리액트: 가장 인기 있는 프론트엔드 라이브러리 혹은 프레임워크이다. 선언적인 패러다임을 따른다. 돔을 직접 수정하기 보단 상태를 변경하여 리액트가 나머지 작업을 수행할 수 있게한다. 데이터가 모델(상태)->뷰로만 흐르게 된다. 리액트는 프레임워크라기 보단 렌더링 라이브러리이다. (상태만 변경하고 렌더링 함수를 호출하듯 라이브러리 느낌도 있다.)
아하! 그렇군요. 준찌~ 
프레임워크를 규정하는 기준은
`명확한 규칙`의 강도라고 보는 게 더 낫겠네요!
그리고 `데이터 바인딩`의 구체적인 방법은 프레임워크와 라이브러리를 가르는 기준이 되긴 어렵겠군요.

배워갑니다 🙏

2022-04-02 15:21 UTC, woose28 requested changes
게으른 중생을 용서하소서...갓찌
리뷰가 너무 늦어서 죄송합니다🙏
이번 글도 역시 많이 배워갈 수 있었어요!
준찌가 정리해준 글을 보니까 저도 이 책을 읽고 싶어지네요ㅎㅎ

코멘트를  몇 가지 남겼는데 가볍게 답변해 주시거나 리액션만 남겨주셔도 됩니다!
책 읽느라  고생 많았어요👍 👍

2022-04-02 15:21 UTC, woose28 commented on frameworkless-frontend/juunzzi/1장_프레임워크에_대한_이야기.md
> +준찌의 사견 : 저도 이 말에 굉장히 공감해요. 뮤지션이 음악을 만들 때, 좋은 음악을 만드는 것에 집중할까요 아님 화성학에 집중할까요? 또 언어를 배울 때 의사소통하는법에 집중해야할까요 아님 문법을 지키는 것에 집중해야할까요. 저도 목적을 잃는게 싫어요. 프레임워크 혹은 디자인패턴 모두 같지 않을까요? 우리의 목표는 사용자에게 좋은 서비스를 제공할 수
> 우리의 목표는 사용자에게 좋은 서비스를 제공할 수 있는 프로덕트를 만드는 것이잖아요. 프레임워크나 디자인패턴에 집착할 필요는 없을 것 같아요.

오늘도 명언을 남기는군요 갓찌

2022-04-02 15:21 UTC, woose28 commented on frameworkless-frontend/juunzzi/1장_프레임워크에_대한_이야기.md
> +제이쿼리 : 현대 웹 개발의 초석 역할을 수행. 만만히 보고 있지만 역사적으로 꽤나 가치있는 녀석이다. (박지성)
ㅋㅋㅋㅋㅋ지성박은 인정이지~!

2022-04-02 15:21 UTC, woose28 commented on frameworkless-frontend/juunzzi/test/2_3list.js
> +};
역시 준찌...
테스트 코드도 만들다니 대단합니다!!

주사율이랑 프레임 개념이 헷갈렸는데, 준찌 글 덕분에 공부를 찾아보고 공부하게됐어요👍

그리고 60 프레임 잘 찍힙니다ㅎㅎ!
<img width="996" alt="60hz 인증" src="https://user-images.githubusercontent.com/52148907/161387182-c3ecc9b8-69f5-47f6-a5ef-3a0095818531.png">

2022-04-02 15:21 UTC, woose28 commented on frameworkless-frontend/juunzzi/project/getTodos.js
> +};
토이 프로젝트 실행시키고 나서 새로 고침할 때마다 todo가 바뀌어서 오잉?? 마술인가 했는데
이런 기능이 있었군요!!

2022-04-02 15:21 UTC, woose28 commented on frameworkless-frontend/juunzzi/2장_렌더링.md
> +코드에 주석으로 남기겠습니다.. (아직 다 못함..)
미션 하면서 토이 프로젝트까지 진행한 그 자체로 대단...

2022-04-02 15:21 UTC, woose28 commented on frameworkless-frontend/juunzzi/2장_렌더링.md
> +순수함수를 사용하는 경우 테스트 가능성, 구성 가능성 같은 많은 장점이 있다.
> 순수하게 함수를 사용해 요소를 돔에 렌더링하는 다양한 방법을 분석해보자.

오호... 책에는 순수 함수를 사용해서 렌더링 함수를 구현한 예시가 여러개 나오나요? 궁금쓰

> 순수함수를 사용하는 경우 테스트 가능성, 구성 가능성 같은 많은 장점이 있다.

순수 함수 사용시 테스트 가능성 공감!
구성 가능성에 대해서는 조금 더 설명이 가능할까요ㅎㅎ

2022-04-02 15:21 UTC, woose28 commented on frameworkless-frontend/juunzzi/2장_렌더링.md
> +웹용 렌더링 엔진을 설계할 때는 가독성과 유지관리성을 염두에 두어야한다. 렌더링은 모든 웹 어플리케이션에서 매우 중요한 작업. 렌더링 엔진을 처음부터 새로 작성하기로 결정했다면 이해하고 발전시키기 쉽게 설계해야함.
성능이 가장 중요할 것이라 생각했는데, 렌더링 엔진 또한 코드이니 기본적으로 가독성과 유지 관리성이 중요하다는 말이군요!

까마득해보이는데 언젠간 렌더링 엔진을 직접 구현하는 날이 오겠죠..ㅎㅎ?
일단 렌더링 원리부터 공부해야게따💫

2022-04-02 15:21 UTC, woose28 commented on frameworkless-frontend/juunzzi/1장_프레임워크에_대한_이야기.md
> +
제약 사항이 있다. 즉, 규칙과 형식이 정해지면 명확하게 코딩을 할 수 있다는 장점이 있다! 그러나 규칙과 형식에 적응하기까지 러닝 커브가 필요하며, 유연함이 떨어지는 단점이 있다!

저는 제약 사항의 장점과 단점이 위와 같다고 생각합니다ㅎㅎ

제 생각이 맞는지도 궁금하고, 프레임워크의 제약 사항에 대한 다른 예시가 궁금하네요!

2022-04-02 18:04 UTC, juunzzi commented on frameworkless-frontend/juunzzi/test/2_3list.js
> +};
ㅋㅋㅋㅋ 일단 코드는 책에 있는 코드 ^^... ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 제가 한것처럼 느껴지시나보네요... 


그리구 저도 프레임에 대해서 굉장히 애매했는데 (FPS 같은 용어) 좋은 링크 발견해서 공유드립니다.  https://tecoble.techcourse.co.kr/post/2021-08-28-event-loop/

2022-04-02 18:05 UTC, juunzzi commented on frameworkless-frontend/juunzzi/2장_렌더링.md
> +순수함수를 사용하는 경우 테스트 가능성, 구성 가능성 같은 많은 장점이 있다.
죄송해요.. .이게 번역본이라 저도 이해가 아직안되었습니다. 그리구 순수하게 함수로만 프로젝트를 하겠다는 건지 아님 진짜 순수함수로 프로젝트를 하겠다는 건지 이 마저도 번역된 말이 너무 어려워서 이해를 못했어요 ㅠㅠㅠㅠ 설명못드릴것같아요 죄송합니다.

2022-04-02 18:06 UTC, juunzzi commented on frameworkless-frontend/juunzzi/2장_렌더링.md
> +웹용 렌더링 엔진을 설계할 때는 가독성과 유지관리성을 염두에 두어야한다. 렌더링은 모든 웹 어플리케이션에서 매우 중요한 작업. 렌더링 엔진을 처음부터 새로 작성하기로 결정했다면 이해하고 발전시키기 쉽게 설계해야함.
책에서 말하는 렌더링 엔진은 브라우저의 렌더링 엔진을 말하는게 아닌것같아요 .. 이 책 너무 말이 번역 느낌이라 어렵습니다.... (책을 읽어본 입장으로서 여기서 말하는 렌더링 엔진은 리액트 라이브러리처럼 렌더링을 하는 모듈?을 말하는 것 같아요..)

2022-04-02 18:07 UTC, juunzzi commented on frameworkless-frontend/juunzzi/1장_프레임워크에_대한_이야기.md
> +
오 저도 맞다고 생각해요.. 프레임워크의 제약 사항이라함은 그냥 규칙같은 거라고 이해했습니다.

예를 들어 MVC Framework가 있다고 가정해봅시다 !! 여기서 이벤트 핸들러는 무조건 컨트롤러 단에서 바인딩 해야돼! 라는 규칙을 코드로서 사용자에게 강조한다면 이런건 제약사항이 되겠죠? (책에서도 이러한 부분을 말하는 것 같습니다 하하... 물론 아닐 수도 있어요.. 책 워딩이 너무 모호하네요..)

2022-04-02 18:20 UTC, woose28 commented on frameworkless-frontend/juunzzi/1장_프레임워크에_대한_이야기.md
> +
예시를 들어주시니 훨씬 명확하네요👍

2022-04-02 18:26 UTC, woose28 commented on frameworkless-frontend/juunzzi/2장_렌더링.md
> +순수함수를 사용하는 경우 테스트 가능성, 구성 가능성 같은 많은 장점이 있다.
오... 책이 번역본이군요
영어를 잘 했으면 원문을 읽는 걸 도전했을 텐데 쩝...

2022-04-02 18:36 UTC, woose28 commented on frameworkless-frontend/juunzzi/test/2_3list.js
> +};
ㅋㅋㅋㅋㅋㅋㅋㅋ책에 있는 코드였군요!

좋은 글 공유 감사합니다!
준찌가 올려주신 글에 eventLoop에 대한 설명부터 requestAnimationFrame과 setTimeout의 비교까지 상세히 나와있네요👍

2022-04-02 18:37 UTC, woose28 commented on frameworkless-frontend/juunzzi/2장_렌더링.md
> +웹용 렌더링 엔진을 설계할 때는 가독성과 유지관리성을 염두에 두어야한다. 렌더링은 모든 웹 어플리케이션에서 매우 중요한 작업. 렌더링 엔진을 처음부터 새로 작성하기로 결정했다면 이해하고 발전시키기 쉽게 설계해야함.
아하 렌더링을 직접 구현한다는 말이 아니었군요!

2022-04-03 00:42 UTC, merged